import { CategoryDefinition } from "@/types/category";

export const TOOL_CATEGORIES: CategoryDefinition[] = [
  { slug: "json", name: "JSON Tools", shortDescription: "Format, validate, minify, and inspect JSON.", longDescription: "Practical JSON tools for debugging APIs, configuration files, and structured data. Processing stays in your browser.", icon: "Braces", relatedCategories: ["encoding", "html"], seoTitle: "JSON Tools - Format, Validate & Minify", seoDescription: "Format, validate, minify, and inspect JSON locally with fast browser-based tools.", indexable: true },
  { slug: "encoding", name: "Encoding Tools", shortDescription: "Encode and decode Base64 and URL data.", longDescription: "Convert text safely between common web encodings with clear errors and local processing.", icon: "Binary", relatedCategories: ["json", "generators"], seoTitle: "Encoding & Decoding Tools", seoDescription: "Encode and decode Base64 and URL-safe text instantly in your browser.", indexable: true },
  { slug: "generators", name: "Generator Tools", shortDescription: "Generate UUIDs and reusable development values.", longDescription: "Create secure, standards-based values for development, testing, and everyday work.", icon: "WandSparkles", relatedCategories: ["encoding", "time"], seoTitle: "Free Online Generator Tools", seoDescription: "Generate UUIDs and useful development values locally without signup.", indexable: true },
  { slug: "time", name: "Date & Time Tools", shortDescription: "Convert Unix timestamps and readable dates.", longDescription: "Translate timestamps, epoch values, ISO dates, and local time representations accurately.", icon: "Clock", relatedCategories: ["generators"], seoTitle: "Date, Time & Unix Timestamp Tools", seoDescription: "Convert Unix timestamps, milliseconds, ISO dates, UTC, and local time online.", indexable: true },
  { slug: "regex", name: "Regex Tools", shortDescription: "Test regular expressions and inspect matches.", longDescription: "Build and test JavaScript regular expressions with explicit patterns, flags, matches, and errors.", icon: "Regex", relatedCategories: ["json", "html"], seoTitle: "Regular Expression Tools", seoDescription: "Test JavaScript regular expressions, flags, and matches with clear browser-based results.", indexable: true },
  { slug: "colors", name: "Color Tools", shortDescription: "Convert and inspect web color values.", longDescription: "Translate colors between formats used in design systems, CSS, and visual interfaces.", icon: "Palette", relatedCategories: ["css", "images"], seoTitle: "Online Color Tools & Converters", seoDescription: "Convert HEX, RGB, and alpha color values for CSS and design work.", indexable: true },
  { slug: "html", name: "HTML Tools", shortDescription: "Format and inspect HTML markup.", longDescription: "Clean up HTML for debugging and review while keeping the source on your device.", icon: "CodeXml", relatedCategories: ["css", "markdown"], seoTitle: "HTML Formatter & Web Tools", seoDescription: "Format and inspect HTML markup locally with free browser-based utilities.", indexable: true },
  { slug: "css", name: "CSS Tools", shortDescription: "Format and clean up CSS stylesheets.", longDescription: "Make CSS easier to read and review using lightweight local formatting tools.", icon: "Paintbrush", relatedCategories: ["html", "colors"], seoTitle: "CSS Formatter & Web Styling Tools", seoDescription: "Format and clean CSS code instantly without sending it to a server.", indexable: true },
  { slug: "markdown", name: "Markdown Tools", shortDescription: "Write Markdown and preview HTML output.", longDescription: "Draft and convert Markdown for documentation, notes, and publishing workflows.", icon: "FileText", relatedCategories: ["html"], seoTitle: "Markdown Editor & Conversion Tools", seoDescription: "Write, preview, and convert Markdown locally in your browser.", indexable: true },

  { slug: "text", name: "Text Tools", shortDescription: "Count, clean, sort, and transform text.", longDescription: "Practical writing and text-cleanup utilities for counting, formatting, deduplicating, sorting, and creating URL-safe text.", icon: "TextCursorInput", relatedCategories: ["markdown", "converters"], seoTitle: "Text Tools - Count, Clean & Convert Text", seoDescription: "Count, clean, sort, deduplicate, and transform text with fast local browser tools.", indexable: true },
  { slug: "converters", name: "Converters", shortDescription: "Convert common data and number formats.", longDescription: "Convert structured data, markup, and number formats with clear validation and local processing where practical.", icon: "ArrowLeftRight", relatedCategories: ["json", "text", "encoding"], seoTitle: "Online Data & Format Converters", seoDescription: "Convert CSV, JSON, Markdown, HTML, XML, binary, decimal, and other formats online.", indexable: true },
  { slug: "calculators", name: "Calculators", shortDescription: "Everyday percentage, discount, markup, and date calculations.", longDescription: "Fast, transparent calculators that show practical results without account creation or unnecessary data collection.", icon: "Calculator", relatedCategories: ["time", "converters"], seoTitle: "Free Online Calculators", seoDescription: "Use percentage, discount, markup, age, and other practical calculators instantly.", indexable: true },
  { slug: "security", name: "Security Tools", shortDescription: "Inspect tokens and generate secure random values.", longDescription: "Privacy-conscious browser tools for JWT inspection and cryptographically random password generation with clear security limitations.", icon: "ShieldCheck", relatedCategories: ["encoding", "generators", "json"], seoTitle: "Security & Identity Tools", seoDescription: "Decode JWT data and generate strong random passwords locally with clear security guidance.", indexable: true },
  { slug: "images", name: "Image Tools", shortDescription: "Compress, resize, and convert images privately.", longDescription: "Optimize JPG, PNG, and WebP images with previews, exact controls, and no file uploads.", icon: "Image", relatedCategories: ["pdf", "colors"], seoTitle: "Image Tools - Compress, Resize & Convert", seoDescription: "Compress, resize, and convert JPG, PNG, and WebP images privately in your browser.", indexable: true },
  { slug: "pdf", name: "PDF Tools", shortDescription: "Merge, split, compress, organize, and convert PDFs.", longDescription: "Work with PDF files locally using merging, extraction, page organization, compression, and image conversion tools.", icon: "FileStack", relatedCategories: ["images"], seoTitle: "PDF Tools - Merge, Split, Compress & Convert", seoDescription: "Merge, split, compress, organize, and convert PDF files locally without uploading them.", indexable: true },
];

export function getCategoryBySlug(slug: string) {
  return TOOL_CATEGORIES.find((category) => category.slug === slug);
}
