import { AlertTriangle, FileLock2, ShieldCheck } from "lucide-react";
import { generateSeoMetadata } from "@/lib/seo/metadata";

export const metadata = generateSeoMetadata({ title: "Security & Local Processing", description: "How DevKitLab validates files, limits browser memory use, and processes supported tools locally.", path: "/security" });

export default function SecurityPage() {
  return <div className="mx-auto max-w-4xl space-y-8 py-6"><div><h1 className="text-4xl font-extrabold tracking-tight text-slate-950 dark:text-white">Security and local processing</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">Straightforward details about what the current product does—and what it does not claim to do.</p></div><div className="grid gap-5 md:grid-cols-3"><SecurityCard icon={<ShieldCheck />} title="Local where labeled" text="Text, image, and PDF tools currently execute in browser memory. Inputs are not sent to a DevKitLab processing API." /><SecurityCard icon={<FileLock2 />} title="File safeguards" text="Upload tools validate supported formats, enforce stated size limits, handle damaged files, and release temporary object URLs." /><SecurityCard icon={<AlertTriangle />} title="Know the limits" text="Local processing does not make untrusted files risk-free. Keep your browser updated and do not process material you are not authorized to use." /></div><section className="rounded-2xl border border-slate-200 p-6 dark:border-slate-800"><h2 className="text-xl font-bold text-slate-950 dark:text-white">Reporting a problem</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">Send reproducible security issues to <a className="font-semibold text-brand-700 hover:underline dark:text-brand-400" href="mailto:support@devkitlab.online?subject=Security%20report">support@devkitlab.online</a>. Do not include credentials or sensitive production data.</p></section></div>;
}

function SecurityCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="text-brand-600">{icon}</div><h2 className="mt-4 font-bold text-slate-950 dark:text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{text}</p></section>; }
